In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np 
from sklearn.datasets import load_digits

digits = load_digits()

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.3, random_state=0)

In [13]:
len(X_train), len(X_test), len(y_train), len(y_test)

(1257, 540, 1257, 540)

In [ ]:
#1. Logistic Regression
#2. SVC
#3. Random Forest Classifier

In [14]:
lr = LogisticRegression()
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9537037037037037

In [15]:
svm = SVC()
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.9907407407407407

In [16]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9685185185185186

In [ ]:
#K fold

In [20]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3, random_state= None, shuffle=False)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [21]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [22]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [23]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)


In [25]:
scores_logistic = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data,digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test))  
    scores_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

    #this same can be done by Cross_val_score function

In [26]:
scores_logistic

[0.8948247078464107, 0.9532554257095158, 0.9098497495826378]

In [27]:
scores_svm

[0.3806343906510851, 0.41068447412353926, 0.5125208681135225]

In [28]:
scores_rf


[0.9298831385642737, 0.9449081803005008, 0.9198664440734557]

In [29]:
from sklearn.model_selection import cross_val_score

In [30]:
#Logistic regression model performance using cross_val_score
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), digits.data, digits.target,cv=3)

array([0.89482471, 0.95325543, 0.90984975])

In [31]:
#svm model performance using cross_val_score
cross_val_score(SVC(gamma='auto'), digits.data, digits.target,cv=3)

array([0.38063439, 0.41068447, 0.51252087])

In [32]:
#random forest performance using cross_val_score
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target,cv=3)
#cross_val_score uses stratifield kfold by default

array([0.92988314, 0.95826377, 0.92654424])

In [33]:
#Parameter tunning using k fold cross validation
scores1 = cross_val_score(RandomForestClassifier(n_estimators=5),digits.data, digits.target, cv=10)
np.average(scores1)

0.8681409062693979

In [34]:
scores2 = cross_val_score(RandomForestClassifier(n_estimators=20),digits.data, digits.target, cv=10)
np.average(scores2)

0.9376660459342023

In [35]:
scores3 = cross_val_score(RandomForestClassifier(n_estimators=30),digits.data, digits.target, cv=10)
np.average(scores3)

0.9371104903786467

In [36]:
scores4 = cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target, cv=10)
np.average(scores4)

0.9432371198013655

In [38]:
#Here we used cross_val_score to fine tune our random forest classifier and figured that having around 40 trees in random forest gives best result.


In [39]:
k = 2+3j

In [40]:
k = complex(2,3)

In [42]:
k = 2+ 3J

In [45]:
7//2

3

In [60]:
num1 = 12
num2_ = "58"
float(num2_)
#print(num1 + str(num2))

58.0

In [51]:
a = 5
b = 3
print(a or b)

5


In [52]:
x = 20 
y = 100
(x** 5 > 150) and (y< 100)

False

In [55]:
x = 20 
y = 100
(x** 5 > 150) & (y< 100)

False

In [61]:
import sys 
print(sys.version)

3.9.5 (v3.9.5:0a7dcbdb13, May  3 2021, 13:17:02) 
[Clang 6.0 (clang-600.0.57)]
